#ifndef KTREM_APP_PROFILE_H
#define KTREM_APP_PROFILE_H

#include "app_state.h"
#include "profile.h"

enum {
    PROFILE_PROMPT_NONE = TERMINAL_PANE_PROFILE_PROMPT_NONE,
    PROFILE_PROMPT_SHELL = TERMINAL_PANE_PROFILE_PROMPT_SHELL,
    PROFILE_PROMPT_CWD = TERMINAL_PANE_PROFILE_PROMPT_WORKING_DIRECTORY,
    PROFILE_PROMPT_FONT_FILE = TERMINAL_PANE_PROFILE_PROMPT_TERMINAL_FONT,
    PROFILE_PROMPT_FONT_SIZE = TERMINAL_PANE_PROFILE_PROMPT_FONT_SIZE,
    PROFILE_PROMPT_SCROLLBACK = TERMINAL_PANE_PROFILE_PROMPT_SCROLLBACK,
    PROFILE_PROMPT_FOREGROUND = TERMINAL_PANE_PROFILE_PROMPT_FOREGROUND,
    PROFILE_PROMPT_BACKGROUND = TERMINAL_PANE_PROFILE_PROMPT_BACKGROUND,
    PROFILE_PROMPT_CURSOR_COLOR = TERMINAL_PANE_PROFILE_PROMPT_CURSOR_COLOR,
    PROFILE_PROMPT_SELECTION_FOREGROUND =
        TERMINAL_PANE_PROFILE_PROMPT_SELECTION_FOREGROUND,
    PROFILE_PROMPT_SELECTION_BACKGROUND =
        TERMINAL_PANE_PROFILE_PROMPT_SELECTION_BACKGROUND
};

void open_profile_prompt(State *app, int kind);
const char *profile_prompt_title(int kind);
void apply_profile_prompt(State *app);
void sync_terminal_theme_defaults(State *app,
                                  TerminalProfileColors old_colors);

#endif
