#ifndef KTREM_APP_COMMANDS_H
#define KTREM_APP_COMMANDS_H

#include "app_state.h"

typedef enum AppCommand {
    APP_COMMAND_NONE = 0,
    APP_COMMAND_NEW_TAB = 1001,
    APP_COMMAND_CLOSE_TAB,
    APP_COMMAND_QUIT,
    APP_COMMAND_COPY,
    APP_COMMAND_PASTE,
    APP_COMMAND_SELECT_ALL,
    APP_COMMAND_FONT_INCREASE,
    APP_COMMAND_FONT_DECREASE,
    APP_COMMAND_FONT_RESET,
    APP_COMMAND_NEXT_TAB,
    APP_COMMAND_PREVIOUS_TAB,
    APP_COMMAND_FIND,
    APP_COMMAND_FIND_NEXT,
    APP_COMMAND_FIND_PREVIOUS,
    APP_COMMAND_PROFILE_SHELL,
    APP_COMMAND_PROFILE_CWD,
    APP_COMMAND_PROFILE_FONT_FILE,
    APP_COMMAND_PROFILE_FONT_SIZE,
    APP_COMMAND_PROFILE_SCROLLBACK,
    APP_COMMAND_PROFILE_FOREGROUND,
    APP_COMMAND_PROFILE_BACKGROUND,
    APP_COMMAND_PROFILE_CURSOR_COLOR,
    APP_COMMAND_PROFILE_SELECTION_FOREGROUND,
    APP_COMMAND_PROFILE_SELECTION_BACKGROUND,
    APP_COMMAND_CURSOR_BLOCK,
    APP_COMMAND_CURSOR_UNDERLINE,
    APP_COMMAND_CURSOR_BAR,
    APP_COMMAND_ABOUT
} AppCommand;

void app_execute_command(State *app, int command);
int app_handle_shortcuts(State *app);

#endif
