#ifndef KTREM_APP_PROFILE_H
#define KTREM_APP_PROFILE_H

#include "app_state.h"
#include "profile.h"

enum {
    PROFILE_PROMPT_NONE = TERMINAL_PANE_PROFILE_PROMPT_NONE,
    PROFILE_PROMPT_SHELL = TERMINAL_PANE_PROFILE_PROMPT_SHELL,
    PROFILE_PROMPT_CWD = TERMINAL_PANE_PROFILE_PROMPT_WORKING_DIRECTORY,
    PROFILE_PROMPT_FONT_FILE = TERMINAL_PANE_PROFILE_PROMPT_TERMINAL_FONT,
    PROFILE_PROMPT_FONT_SIZE = TERMINAL_PANE_PROFILE_PROMPT_FONT_SIZE,
    PROFILE_PROMPT_SCROLLBACK = TERMINAL_PANE_PROFILE_PROMPT_SCROLLBACK,
    PROFILE_PROMPT_FOREGROUND = TERMINAL_PANE_PROFILE_PROMPT_FOREGROUND,
    PROFILE_PROMPT_BACKGROUND = TERMINAL_PANE_PROFILE_PROMPT_BACKGROUND,
    PROFILE_PROMPT_CURSOR_COLOR = TERMINAL_PANE_PROFILE_PROMPT_CURSOR_COLOR,
    PROFILE_PROMPT_SELECTION_FOREGROUND =
        TERMINAL_PANE_PROFILE_PROMPT_SELECTION_FOREGROUND,
    PROFILE_PROMPT_SELECTION_BACKGROUND =
        TERMINAL_PANE_PROFILE_PROMPT_SELECTION_BACKGROUND,
    PROFILE_PROMPT_DYNAMIC_TITLE_MODE =
        TERMINAL_PANE_PROFILE_PROMPT_DYNAMIC_TITLE_MODE,
    PROFILE_PROMPT_BACKSPACE_BINDING =
        TERMINAL_PANE_PROFILE_PROMPT_BACKSPACE_BINDING,
    PROFILE_PROMPT_DELETE_BINDING =
        TERMINAL_PANE_PROFILE_PROMPT_DELETE_BINDING,
    PROFILE_PROMPT_AMBIGUOUS_WIDTH =
        TERMINAL_PANE_PROFILE_PROMPT_AMBIGUOUS_WIDTH,
    PROFILE_PROMPT_ALLOW_BOLD =
        TERMINAL_PANE_PROFILE_PROMPT_ALLOW_BOLD,
    PROFILE_PROMPT_UNLIMITED_SCROLLBACK =
        TERMINAL_PANE_PROFILE_PROMPT_UNLIMITED_SCROLLBACK,
    PROFILE_PROMPT_AUTO_HIDE_MOUSE =
        TERMINAL_PANE_PROFILE_PROMPT_AUTO_HIDE_MOUSE,
    PROFILE_PROMPT_MIDDLE_CLICK_CLOSE_TAB =
        TERMINAL_PANE_PROFILE_PROMPT_MIDDLE_CLICK_CLOSE_TAB,
    PROFILE_PROMPT_ALWAYS_SHOW_TABS =
        TERMINAL_PANE_PROFILE_PROMPT_ALWAYS_SHOW_TABS,
    PROFILE_PROMPT_DISABLE_MENU_MNEMONICS =
        TERMINAL_PANE_PROFILE_PROMPT_DISABLE_MENU_MNEMONICS,
    PROFILE_PROMPT_DISABLE_MENU_SHORTCUT =
        TERMINAL_PANE_PROFILE_PROMPT_DISABLE_MENU_SHORTCUT,
    PROFILE_PROMPT_DISABLE_HELP_SHORTCUT =
        TERMINAL_PANE_PROFILE_PROMPT_DISABLE_HELP_SHORTCUT,
    PROFILE_PROMPT_BACKGROUND_OPACITY =
        TERMINAL_PANE_PROFILE_PROMPT_BACKGROUND_OPACITY,
    PROFILE_PROMPT_BACKGROUND_IMAGE =
        TERMINAL_PANE_PROFILE_PROMPT_BACKGROUND_IMAGE
};

void open_profile_prompt(State *app, int kind);
const char *profile_prompt_title(int kind);
void apply_profile_prompt(State *app);
void sync_terminal_theme_defaults(State *app,
                                  TerminalProfileColors old_colors);

#endif
